### ISSUE TITLE
General Visual Improvments

### ISSUE THREAD

**Issue by GalHorowitz** [emimontesdeoca/Backcraft#1]
Hello, I like the concept of this program very much. There are just a few things I think could improve it visually.
![alt text](https://image.prntscr.com/image/68CggduLSj6uFQRj_Y0SEQ.png "Visual Improvments")

**Comment by emimontesdeoca** [comment]
Good ideas right here, I'll be working to add them. 

Thanks!

**Comment by emimontesdeoca** [comment]
New UI is done in recent commits.
