### ISSUE TITLE
Do not re-backup if no changes

### ISSUE THREAD

**Issue by GalHorowitz** [emimontesdeoca/Backcraft#2]
To prevent the backup of the folder if no file were changed, you can use the following peice of code:
```cs
using System;
using System.Text;
using System.Security.Cryptography;
using System.IO;
using System.Linq;

...

public static string CreateMd5ForFolder(string path)
{
    // assuming you want to include nested folders
    var files = Directory.GetFiles(path, "*.*", SearchOption.AllDirectories)
                         .OrderBy(p => p).ToList();

    MD5 md5 = MD5.Create();

    for(int i = 0; i < files.Count; i++)
    {
        string file = files[i];

        // hash path
        string relativePath = file.Substring(path.Length + 1);
        byte[] pathBytes = Encoding.UTF8.GetBytes(relativePath.ToLower());
        md5.TransformBlock(pathBytes, 0, pathBytes.Length, pathBytes, 0);

        // hash contents
        byte[] contentBytes = File.ReadAllBytes(file);
        if (i == files.Count - 1)
            md5.TransformFinalBlock(contentBytes, 0, contentBytes.Length);
        else
            md5.TransformBlock(contentBytes, 0, contentBytes.Length, contentBytes, 0);
    }

    return BitConverter.ToString(md5.Hash).Replace("-", "").ToLower();
}
```
Credit to [Dunc](https://stackoverflow.com/users/188926/dunc)

This will generate a MD5 hash to any folder including the contents.
You can then save this MD5 hash, and when you want to backup again, regenerate the hash, and compare it to the saved one. (If equal do not backup)

**Comment by emimontesdeoca** [comment]
In the list of things to do, this is surely the first one. 

Going to add it on the next version, thanks for the code!

**Comment by emimontesdeoca** [comment]
Fixed this.

Backcraft now checks the MD5 before making a copy of the folder: if they match, folder is IGNORED, if they do not match, folder is copied and the value of the folder's MD5 in files.txt is changed to prevent future backups.

The code was really useful, thanks!
